/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const EffectScope: typeof import('vue')['EffectScope']
  const POST_GAME_REFRESH_DELAYS_MS: typeof import('../src/shared/composables/game/postGameMatchRefresh')['POST_GAME_REFRESH_DELAYS_MS']
  const acceptHMRUpdate: typeof import('pinia')['acceptHMRUpdate']
  const cancelPendingMatchAnalysis: typeof import('../src/shared/composables/game/useMatchAnalysis')['cancelPendingMatchAnalysis']
  const computed: typeof import('vue')['computed']
  const createApp: typeof import('vue')['createApp']
  const createPinia: typeof import('pinia')['createPinia']
  const customRef: typeof import('vue')['customRef']
  const defineAsyncComponent: typeof import('vue')['defineAsyncComponent']
  const defineComponent: typeof import('vue')['defineComponent']
  const defineStore: typeof import('pinia')['defineStore']
  const effectScope: typeof import('vue')['effectScope']
  const getActivePinia: typeof import('pinia')['getActivePinia']
  const getCurrentInstance: typeof import('vue')['getCurrentInstance']
  const getCurrentScope: typeof import('vue')['getCurrentScope']
  const getLatestMatchId: typeof import('../src/shared/composables/game/postGameMatchRefresh')['getLatestMatchId']
  const h: typeof import('vue')['h']
  const inject: typeof import('vue')['inject']
  const isProxy: typeof import('vue')['isProxy']
  const isReactive: typeof import('vue')['isReactive']
  const isReadonly: typeof import('vue')['isReadonly']
  const isRef: typeof import('vue')['isRef']
  const mapActions: typeof import('pinia')['mapActions']
  const mapGetters: typeof import('pinia')['mapGetters']
  const mapState: typeof import('pinia')['mapState']
  const mapStores: typeof import('pinia')['mapStores']
  const mapWritableState: typeof import('pinia')['mapWritableState']
  const markRaw: typeof import('vue')['markRaw']
  const nextTick: typeof import('vue')['nextTick']
  const onActivated: typeof import('vue')['onActivated']
  const onBeforeMount: typeof import('vue')['onBeforeMount']
  const onBeforeRouteLeave: typeof import('vue-router')['onBeforeRouteLeave']
  const onBeforeRouteUpdate: typeof import('vue-router')['onBeforeRouteUpdate']
  const onBeforeUnmount: typeof import('vue')['onBeforeUnmount']
  const onBeforeUpdate: typeof import('vue')['onBeforeUpdate']
  const onDeactivated: typeof import('vue')['onDeactivated']
  const onErrorCaptured: typeof import('vue')['onErrorCaptured']
  const onMounted: typeof import('vue')['onMounted']
  const onRenderTracked: typeof import('vue')['onRenderTracked']
  const onRenderTriggered: typeof import('vue')['onRenderTriggered']
  const onScopeDispose: typeof import('vue')['onScopeDispose']
  const onServerPrefetch: typeof import('vue')['onServerPrefetch']
  const onUnmounted: typeof import('vue')['onUnmounted']
  const onUpdated: typeof import('vue')['onUpdated']
  const onWatcherCleanup: typeof import('vue')['onWatcherCleanup']
  const provide: typeof import('vue')['provide']
  const reactive: typeof import('vue')['reactive']
  const readonly: typeof import('vue')['readonly']
  const ref: typeof import('vue')['ref']
  const refreshStaticCatalogsOnVersionChange: typeof import('../src/shared/composables/data/useVersionedData')['refreshStaticCatalogsOnVersionChange']
  const resolveComponent: typeof import('vue')['resolveComponent']
  const runPostGameRefresh: typeof import('../src/shared/composables/game/postGameMatchRefresh')['runPostGameRefresh']
  const runeSelectionFromOpgg: typeof import('../src/shared/composables/game/useBuildApplication')['runeSelectionFromOpgg']
  const runeSnapshotFromOpgg: typeof import('../src/shared/composables/game/useBuildApplication')['runeSnapshotFromOpgg']
  const setActivePinia: typeof import('pinia')['setActivePinia']
  const setMapStoreSuffix: typeof import('pinia')['setMapStoreSuffix']
  const shallowReactive: typeof import('vue')['shallowReactive']
  const shallowReadonly: typeof import('vue')['shallowReadonly']
  const shallowRef: typeof import('vue')['shallowRef']
  const storeToRefs: typeof import('pinia')['storeToRefs']
  const stores: typeof import('../src/shared/stores/index')['default']
  const toRaw: typeof import('vue')['toRaw']
  const toRef: typeof import('vue')['toRef']
  const toRefs: typeof import('vue')['toRefs']
  const toValue: typeof import('vue')['toValue']
  const triggerRef: typeof import('vue')['triggerRef']
  const unref: typeof import('vue')['unref']
  const useActivityLogger: typeof import('../src/shared/composables/utils/useActivityLogger')['useActivityLogger']
  const useActivityStore: typeof import('../src/shared/stores/core/activityStore')['useActivityStore']
  const useAiAnalysis: typeof import('../src/shared/composables/game/useAiAnalysis')['useAiAnalysis']
  const useAiSettingsStore: typeof import('../src/shared/stores/features/aiSettingsStore')['useAiSettingsStore']
  const useApp: typeof import('../src/shared/composables/app/useApp')['useApp']
  const useAppEvents: typeof import('../src/shared/composables/app/useAppEvents')['useAppEvents']
  const useAppInitialization: typeof import('../src/shared/composables/app/useAppInitialization')['useAppInitialization']
  const useAttrs: typeof import('vue')['useAttrs']
  const useAutoBuild: typeof import('../src/shared/composables/game/useAutoBuild')['useAutoBuild']
  const useAutoFunctionStore: typeof import('../src/shared/stores/features/autoFunctionStore')['useAutoFunctionStore']
  const useBootstrapStaticData: typeof import('../src/shared/composables/data/useVersionedData')['useBootstrapStaticData']
  const useBuildApplication: typeof import('../src/shared/composables/game/useBuildApplication')['useBuildApplication']
  const useBuildPresetStore: typeof import('../src/shared/stores/features/buildPresetStore')['useBuildPresetStore']
  const useChampSelect: typeof import('../src/shared/composables/game/useChampSelect')['useChampSelect']
  const useChampSelectAutomation: typeof import('../src/shared/composables/game/useChampSelectAutomation')['useChampSelectAutomation']
  const useChampSelectManager: typeof import('../src/shared/composables/game/useChampSelectManager')['useChampSelectManager']
  const useChampionDetails: typeof import('../src/shared/composables/data/useVersionedData')['useChampionDetails']
  const useChampions: typeof import('../src/shared/composables/data/useVersionedData')['useChampions']
  const useCommunityDragonPerksQuery: typeof import('../src/shared/composables/data/useVersionedData')['useCommunityDragonPerksQuery']
  const useConnection: typeof import('../src/shared/composables/connection/useConnection')['useConnection']
  const useConnectionStore: typeof import('../src/shared/stores/core/connectionStore')['useConnectionStore']
  const useCssModule: typeof import('vue')['useCssModule']
  const useCssVars: typeof import('vue')['useCssVars']
  const useDataStore: typeof import('../src/shared/stores/core/dataStore')['useDataStore']
  const useDebouncedNumberModel: typeof import('../src/shared/composables/utils/useDebouncedNumberModel')['useDebouncedNumberModel']
  const useDeviceWebSocket: typeof import('../src/shared/composables/app/useDeviceWebSocket')['useDeviceWebSocket']
  const useErrorHandler: typeof import('../src/shared/composables/utils/useErrorHandler')['useErrorHandler']
  const useEventBus: typeof import('../src/shared/composables/utils/useEventBus')['useEventBus']
  const useFormatters: typeof import('../src/shared/composables/utils/useFormatters')['useFormatters']
  const useGameAssets: typeof import('../src/shared/composables/game/useGameAssets')['useGameAssets']
  const useGameEvents: typeof import('../src/shared/composables/utils/useEventBus')['useGameEvents']
  const useGamePhaseManager: typeof import('../src/shared/composables/game/useGamePhaseManager')['useGamePhaseManager']
  const useGameStore: typeof import('../src/shared/stores/features/gameStore')['useGameStore']
  const useGameVersion: typeof import('../src/shared/composables/data/useVersionedData')['useGameVersion']
  const useId: typeof import('vue')['useId']
  const useItems: typeof import('../src/shared/composables/data/useVersionedData')['useItems']
  const useLink: typeof import('vue-router')['useLink']
  const useLoading: typeof import('../src/shared/composables/utils/useLoading')['useLoading']
  const useMatchAnalysis: typeof import('../src/shared/composables/game/useMatchAnalysis')['useMatchAnalysis']
  const useMatchFilter: typeof import('../src/shared/composables/game/useMatchFilter')['useMatchFilter']
  const useMatchmaking: typeof import('../src/shared/composables/game/useMatchmaking')['useMatchmaking']
  const useMatchmakingStore: typeof import('../src/shared/stores/features/matchmakingStore')['useMatchmakingStore']
  const useModel: typeof import('vue')['useModel']
  const usePersonalMatchAnalysisStore: typeof import('../src/shared/stores/features/personalMatchAnalysisStore')['usePersonalMatchAnalysisStore']
  const usePositionAnalysis: typeof import('../src/shared/composables/game/usePositionAnalysis')['usePositionAnalysis']
  const useQueues: typeof import('../src/shared/composables/data/useVersionedData')['useQueues']
  const useReactiveEvent: typeof import('../src/shared/composables/utils/useEventBus')['useReactiveEvent']
  const useRoute: typeof import('vue-router')['useRoute']
  const useRouter: typeof import('vue-router')['useRouter']
  const useRuneData: typeof import('../src/shared/composables/game/useRuneData')['useRuneData']
  const useSearchHistoryStore: typeof import('../src/shared/stores/features/searchHistoryStore')['useSearchHistoryStore']
  const useSearchMatches: typeof import('../src/shared/composables/game/useSearchMatches')['useSearchMatches']
  const useSessionStore: typeof import('../src/shared/stores/features/sessionStore')['useSessionStore']
  const useSettingsStore: typeof import('../src/shared/stores/ui/settingsStore')['useSettingsStore']
  const useSlots: typeof import('vue')['useSlots']
  const useStaticCatalogMeta: typeof import('../src/shared/composables/data/useVersionedData')['useStaticCatalogMeta']
  const useStaticData: typeof import('../src/shared/composables/data/useVersionedData')['useStaticData']
  const useSummonerAndMatchUpdater: typeof import('../src/shared/composables/game/useSummonerAndMatchUpdater')['useSummonerAndMatchUpdater']
  const useSummonerSpells: typeof import('../src/shared/composables/data/useVersionedData')['useSummonerSpells']
  const useTemplateRef: typeof import('vue')['useTemplateRef']
  const watch: typeof import('vue')['watch']
  const watchEffect: typeof import('vue')['watchEffect']
  const watchPostEffect: typeof import('vue')['watchPostEffect']
  const watchSyncEffect: typeof import('vue')['watchSyncEffect']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { PostGameRefreshOutcome } from '../src/shared/composables/game/postGameMatchRefresh'
  import('../src/shared/composables/game/postGameMatchRefresh')
  // @ts-ignore
  export type { RecommendationContext } from '../src/shared/composables/game/useBuildApplication'
  import('../src/shared/composables/game/useBuildApplication')
  // @ts-ignore
  export type { PerkStyle, PerkSlot, Perk } from '../src/shared/composables/game/useRuneData'
  import('../src/shared/composables/game/useRuneData')
  // @ts-ignore
  export type { DebouncedNumberModelOptions } from '../src/shared/composables/utils/useDebouncedNumberModel'
  import('../src/shared/composables/utils/useDebouncedNumberModel')
  // @ts-ignore
  export type { ErrorInfo, RetryConfig } from '../src/shared/composables/utils/useErrorHandler'
  import('../src/shared/composables/utils/useErrorHandler')
  // @ts-ignore
  export type { AiSettingsPublic } from '../src/shared/stores/features/aiSettingsStore'
  import('../src/shared/stores/features/aiSettingsStore')
  // @ts-ignore
  export type { AutoFunctions, AutoFunctionConfig, AutoSelectConfig, AutoBanConfig } from '../src/shared/stores/features/autoFunctionStore'
  import('../src/shared/stores/features/autoFunctionStore')
  // @ts-ignore
  export type { AutoBuildPolicy } from '../src/shared/stores/features/buildPresetStore'
  import('../src/shared/stores/features/buildPresetStore')
}
