/**
 * 全局类型声明 - 由 scripts/sync-types.mjs 自动生成
 *
 * ************************************************
 * *                                               *
 * *           !!!   请勿手动修改此文件   !!!            *
 * *                                               *
 * *************************************************
 *
 * 如需更新，请运行 'odescripts/sync-types.mjs'
 */

// --- 从 AnalysisChampionStats.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 分析用英雄统计数据（包含英雄名称）
 */
type AnalysisChampionStats = { championId: number, championName: string, games: number, wins: number, winRate: number, };


// --- 从 BanInfo.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type BanInfo = { championId: number | null, pickTurn: number | null, };


// --- 从 ChampSelectAction.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type ChampSelectAction = { actorCellId: number | null, championId: number | null, completed: boolean, id: number, isAllyAction: boolean | null, isInProgress: boolean | null, pickTurn: number | null, type: string, isCurrentUser: boolean | null, };


// --- 从 ChampSelectBans.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type ChampSelectBans = { myTeamBans: Array<number | null>, theirTeamBans: Array<number | null>, };


// --- 从 ChampSelectPlayer.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type ChampSelectPlayer = { cellId: number, puuid: string | null, summonerId: string | null, championId: number | null, championPickIntent: number | null, selectedSkinId: number | null, spell1Id: number | null, spell2Id: number | null, assignedPosition: string | null, displayName: string | null, tagLine: string | null, profileIconId: bigint | null, tier: string | null, recentMatches: Array<SimpleMatchInfo> | null, };


// --- 从 ChampSelectSession.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type ChampSelectSession = { localPlayerCellId: number, myTeam: Array<ChampSelectPlayer>, theirTeam: Array<ChampSelectPlayer>, bans: ChampSelectBans, timer: ChampSelectTimer, actions: Array<Array<ChampSelectAction>>, };


// --- 从 ChampSelectTimer.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type ChampSelectTimer = { phase: string, };


// --- 从 ConnectionInfo.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type ConnectionInfo = { state: ConnectionState, consecutive_failures: number, error_message: string | null, };


// --- 从 ConnectionState.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type ConnectionState = "Connected" | "ProcessFound" | "Unstable" | "AuthExpired" | "Disconnected";


// --- 从 GameAdvice.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 游戏建议（v3.0 新增）⭐
 */
type GameAdvice = { title: string, problem: string, evidence: string, suggestions: Array<string>, priority: number, category: AdviceCategory, perspective: AdvicePerspective, affectedRole: string | null, targetPlayer: string | null, };


// --- 从 GameDetail.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type GameDetail = { gameId: number, gameDuration: number, gameCreation: number, gameMode: string, gameType: string, gameVersion: string, mapId: number, queueId: number, teams: Array<TeamInfo>, participants: Array<ParticipantInfo>, blueTeamStats: TeamStats, redTeamStats: TeamStats, bestPlayerChampionId: number, maxDamage: number, maxTankChampionId: number, maxTank: number, maxStreakChampionId: number, maxStreak: number, };


// --- 从 LiveClientPlayer.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type LiveClientPlayer = { summonerName: string, championName: string, isBot: boolean, isDead: boolean, items: any[], level: number, position: string, rawChampionName: string, respawnTimer: number, runes: any, scores: any, skinID: number, summonerSpells: any, team: string, };


// --- 从 LobbyInfo.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type LobbyInfo = { canStartActivity: boolean, gameConfig: any, invitations: any[], localMember: LobbyMember | null, members: Array<LobbyMember>, mucJwtDto: any, multiUserChatId: string, multiUserChatPassword: string, partyId: string, partyType: string, restrictions: any[], warnings: any[], };


// --- 从 LobbyMember.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type LobbyMember = { summonerId: string, displayName: string, puuid: string, summonerName: string, summonerLevel: number, summonerIconId: number, isBot: boolean, isLeader: boolean, isSpectator: boolean, ready: boolean, botChampionId: number, botDifficulty: string, botId: string, botPosition: string, firstPositionPreference: string, secondPositionPreference: string, allowedChangeActivity: boolean, allowedInviteOthers: boolean, allowedKickOthers: boolean, allowedStartActivity: boolean, };


// --- 从 MatchInfo.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type MatchInfo = { matchId: string, players: Array<PlayerInfo>, };


// --- 从 MatchPerformance.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 单场比赛表现
 */
type MatchPerformance = { gameId: number | undefined, win: boolean, championId: number, championName: string, kills: number, deaths: number, assists: number, kda: number, gameDuration: number | null, gameCreation: number | undefined, queueId: number | undefined, gameMode: string | null, role: string, lane: string, position: string, };


// --- 从 OpggChampionBuild.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * OP.GG 英雄详细数据
 */
type OpggChampionBuild = { summary: OpggChampionSummary, summonerSpells: Array<OpggSummonerSpell>, championSkills: OpggSkills, items: OpggItems, counters: OpggCounters, perks: Array<OpggPerk>, };


// --- 从 OpggChampionSummary.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 英雄摘要信息
 */
type OpggChampionSummary = { name: string, championId: number, icon: string, position: string, winRate: number | null, pickRate: number | null, banRate: number | null, kda: number | null, tier: string | null, rank: number | null, };


// --- 从 OpggCounter.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 克制英雄
 */
type OpggCounter = { championId: number, winRate: number, };


// --- 从 OpggCounters.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 克制关系
 */
type OpggCounters = { strongAgainst: Array<OpggCounter>, weakAgainst: Array<OpggCounter>, };


// --- 从 OpggItem.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 装备项目
 */
type OpggItem = { id: number, ids: Array<number>, icons: Array<string>, win: number, play: number, pickRate: number, };


// --- 从 OpggItems.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 装备数据
 */
type OpggItems = { startItems: Array<OpggItem>, coreItems: Array<OpggItem>, boots: Array<OpggItem>, lastItems: Array<OpggItem>, };


// --- 从 OpggPerk.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 符文配置
 */
type OpggPerk = { primaryId: number, secondaryId: number, perks: Array<number>, win: number, play: number, pickRate: number, };


// --- 从 OpggSkills.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 英雄技能
 */
type OpggSkills = { masteries: Array<string>, order: Array<string>, play: number, win: number, pickRate: number, };


// --- 从 OpggSummonerSpell.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 召唤师技能
 */
type OpggSummonerSpell = { spellId: number, ids: Array<number>, win: number, play: number, pickRate: number, };


// --- 从 OpggTierList.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 层级列表
 */
type OpggTierList = { meta: OpggTierListMeta, data: Array<OpggTierListItem>, };


// --- 从 OpggTierListItem.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 层级列表项
 */
type OpggTierListItem = { championId: number, name: string, tier: string, rank: number, winRate: number, pickRate: number, banRate: number, };


// --- 从 OpggTierListMeta.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 层级列表元数据
 */
type OpggTierListMeta = { version: string, region: string, mode: string, tier: string, };


// --- 从 ParticipantInfo.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type ParticipantInfo = { participantId: number, championId: number, summonerName: string, profileIconId: number, teamId: number, rankTier: string | null, stats: ParticipantStats, score: number | null, };


// --- 从 ParticipantStats.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type ParticipantStats = { kills: number, deaths: number, assists: number, champLevel: number, goldEarned: number, totalDamageDealtToChampions: number, totalDamageTaken: number, visionScore: number, item0: number | null, item1: number | null, item2: number | null, item3: number | null, item4: number | null, item5: number | null, item6: number | null, };


// --- 从 PlayerAnalysisData.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 玩家完整分析数据（包含战绩）
 */
type PlayerAnalysisData = { cellId: number, displayName: string, summonerId: string | null, puuid: string | null, isLocal: boolean, isBot: boolean, championId: number | null, championName: string | null, championPickIntent: number | null, position: string | null, tier: string | null, profileIconId: number | null, tagLine: string | null, spell1Id: bigint | null, spell2Id: bigint | null, matchStats: PlayerMatchStats | null, };


// --- 从 PlayerInfo.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type PlayerInfo = { summonerName: string, championId: number, teamId: number, };


// --- 从 PlayerMatchStats.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 玩家战绩统计（完整版 - 包含所有分析数据）
 */
type PlayerMatchStats = { totalGames: number, wins: number, losses: number, winRate: number, avgKills: number, avgDeaths: number, avgAssists: number, avgKda: number, todayGames: number, todayWins: number, dpm: number, cspm: number, vspm: number, traits: Array<SummonerTrait>, favoriteChampions: Array<AnalysisChampionStats>, recentPerformance: Array<MatchPerformance>, advice?: Array<GameAdvice>, };


// --- 从 QueueStats.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type QueueStats = { tier: string, division: string, leaguePoints: number, wins: number, losses: number, };


// --- 从 RankInfo.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type RankInfo = { soloTier: string | null, soloDivision: string | null, soloLp: number | null, soloWins: number | null, soloLosses: number | null, flexTier: string | null, flexDivision: string | null, flexLp: number | null, flexWins: number | null, flexLosses: number | null, };


// --- 从 RankedStats.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type RankedStats = { queueMap: { [key in string]?: QueueStats }, };


// --- 从 RecentGame.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 最近游戏信息
 */
type RecentGame = { gameId: number, championId: number, gameMode: string, win: boolean, kills: number, deaths: number, assists: number, gameDuration: number, gameCreation: number, queueId: number, performanceRating: string, };


// --- 从 SimpleMatchInfo.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 简单对局信息
 */
type SimpleMatchInfo = { gameId: number, championId: number, win: boolean, kills: number, deaths: number, assists: number, gameCreation: number, };


// --- 从 SummonerInfo.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type SummonerInfo = { displayName: string, gameName: string | null, tagLine: string | null, summonerLevel: number, profileIconId: number, puuid: string, accountId: string, summonerId: string, xpSinceLastLevel: number, xpUntilNextLevel: number, percentCompleteForNextLevel: number | null, gameStatus: string | null, availability: string | null, challengePoints: string | null, challengeCrystalLevel: string | null, soloRankTier: string | null, soloRankDivision: string | null, soloRankWins: number | null, soloRankLosses: number | null, soloRankLp: number | null, flexRankTier: string | null, flexRankDivision: string | null, flexRankWins: number | null, flexRankLosses: number | null, flexRankLp: number | null, highestRankThisSeason: string | null, currentPerkPage: string | null, primaryStyleId: number | null, subStyleId: number | null, selectedPerkIds: Array<number> | null, };


// --- 从 SummonerTrait.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 召唤师特征标签
 */
type SummonerTrait = { name: string, description: string, score: number, type: string, };


// --- 从 SummonerWithMatches.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type SummonerWithMatches = { displayName: string, summonerInfo: SummonerInfo, matches: PlayerMatchStats, };


// --- 从 TeamAnalysisData.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 队伍分析数据
 */
type TeamAnalysisData = { myTeam: Array<PlayerAnalysisData>, enemyTeam: Array<PlayerAnalysisData>, localPlayerCellId: number, gamePhase: string, queueId: number, isCustomGame: boolean, actions: Array<Array<ChampSelectAction>> | null, bans: ChampSelectBans | null, timer: ChampSelectTimer | null, };


// --- 从 TeamInfo.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type TeamInfo = { teamId: number | null, win: string | null, bans: Array<BanInfo>, baronKills: number | null, dragonKills: number | null, towerKills: number | null, inhibitorKills: number | null, };


// --- 从 TeamStats.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type TeamStats = { kills: number, goldEarned: number, totalDamageDealtToChampions: number, visionScore: number, };


