/**
 * 全局类型声明 - 由 scripts/sync-types.mjs 自动生成
 *
 * ************************************************
 * *                                               *
 * *           !!!   请勿手动修改此文件   !!!            *
 * *                                               *
 * *************************************************
 *
 * 如需更新，请运行 'pnpm types'
 */

// --- 从 ActivityBucketCount.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type ActivityBucketCount = {
/**
 * dead / base / ownJungle / enemyJungle / riverOrObjective / lane / unknown
 */
activity: string, label: string, count: number, };

// --- 从 ActivityContext.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 目标玩家在事件时刻的粗活动
 */
type ActivityContext = "dead" | "base" | "ownJungle" | "enemyJungle" | "riverOrObjective" | "lane" | "unknown";

// --- 从 AdviceCategory.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 建议分类
 */
type AdviceCategory = "Laning" | "Farming" | "Teamfight" | "Vision" | "Positioning" | "Decision" | "Champion";

// --- 从 AdvicePerspective.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 建议视角
 */
type AdvicePerspective = "SelfImprovement" | "Targeting" | "Collaboration";

// --- 从 AiInsight.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 模型必须返回的结构化解读
 */
type AiInsight = { summary: string, confidence: number, findings: Array<AiInsightFinding>, suggestions: Array<AiInsightSuggestion>, };

// --- 从 AiInsightFinding.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type AiInsightFinding = { title: string, detail: string, evidenceGameIds: number[], confidence: number, };

// --- 从 AiInsightSuggestion.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type AiInsightSuggestion = { title: string, actions: Array<string>, evidenceGameIds: number[], priority: number, };

// --- 从 AiPromptBundle.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 发给模型的脱敏证据摘要（禁止含 PUUID / 召唤师名 / 完整时间线）
 */
type AiPromptBundle = { analyzedGames: number, rankedGames: number, mainPosition: string | null, winRate: number | null, summaries: Array<AiPromptSummary>, traits: Array<AiPromptTrait>, diagnostics: Array<string>, };

// --- 从 AiPromptSummary.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type AiPromptSummary = { queueId: bigint, position: string, sampleSize: number, winRate: number, avgDeaths: number | null, earlyCsPerMin: number | null, laningAdvantage: number | null, };

// --- 从 AiPromptTrait.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type AiPromptTrait = { key: string, name: string, description: string, sentiment: string, sampleCount: number, supportsConclusion: boolean, evidenceGameIds: number[], };

// --- 从 AiPublicSettings.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 前端可见的 AI 配置（绝不包含明文 Key）
 */
type AiPublicSettings = { enabled: boolean, provider: string, baseUrl: string, model: string,
/**
 * 仅表示是否已配置 Key，永不回传明文
 */
hasApiKey: boolean, };

// --- 从 AnalysisCapabilities.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 结果能力声明（前端据此决定展示什么、隐藏什么）
 */
type AnalysisCapabilities = {
/**
 * 基础统计始终可用
 */
basicStats: boolean,
/**
 * 位置维度的深度拆分是否可用
 */
positionBreakdown: boolean,
/**
 * 深度层结论是否可用
 */
deepAnalysis: boolean, timeline: boolean, opponent: boolean, teammate: boolean, selfImprovement: boolean,
/**
 * 是否存在（或可能存在）排位深度证据
 */
rankedDeepEvidence: boolean,
/**
 * 本地 AI 能力是否可用
 */
localAi: boolean, };

// --- 从 AnalysisChampionStats.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 分析用英雄统计数据（包含英雄名称）
 */
type AnalysisChampionStats = { championId: number, championName: string, games: number, wins: number, winRate: number, };

// --- 从 AnalysisDegradationCode.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 降级原因码
 */
type AnalysisDegradationCode = "analysisDisabled" | "simpleDepthRequested" | "funModeDeepUnsupported" | "perGameDepthApplied" | "timelineDisabledByFeatureFlag" | "opponentDisabledByFeatureFlag" | "teammateDisabledByFeatureFlag" | "selfImprovementDisabledByFeatureFlag" | "gameCountCapped" | "localAiRequiresRankedDeepEvidence" | "noMatchesInScope" | "insufficientMatchesInScope" | "evidenceExtractionFailed" | "timelineDataUnavailable" | "insufficientEvidenceSample";

// --- 从 AnalysisDepth.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 分析深度枚举
 */
type AnalysisDepth = "simple" | "deep";

// --- 从 AnalysisDiagnostic.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 降级诊断（用于向用户解释「为什么没有这个结论」）
 */
type AnalysisDiagnostic = {
/**
 * 原因码（前端可据此本地化/分组）
 */
code: AnalysisDegradationCode,
/**
 * 人类可读原因
 */
message: string,
/**
 * 受影响的功能项
 */
feature?: AnalysisFeature, };

// --- 从 AnalysisFeature.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 受降级影响的功能项
 */
type AnalysisFeature = "deepAnalysis" | "timeline" | "opponent" | "teammate" | "selfImprovement" | "localAi" | "gameCount";

// --- 从 AnalysisFeatureFlags.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 分析功能开关（IPC `MatchAnalysisRequest.features`）
 */
type AnalysisFeatureFlags = {
/**
 * 智能分析总开关：false 时只产出基础统计
 */
enabled: boolean,
/**
 * 时间线分析（分阶段 CS/经济/经验差）
 */
timeline: boolean,
/**
 * 对手分析
 */
opponent: boolean,
/**
 * 队友分析
 */
teammate: boolean,
/**
 * 自我提升分析
 */
selfImprovement: boolean, };

// --- 从 AnalysisMode.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 分析模式（由前端用户选择）
 */
type AnalysisMode = "soloRanked" | "flexRanked" | "mixedRanked" | "aram" | "normals" | "allModes";

// --- 从 AnalysisPolicy.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 分析策略（唯一推导产物）
 *
 * 由 `policy::resolve_analysis_policy` 生成，下游 fetcher / orchestrator / AI
 * 只读取该结构，不再各自判断模式与深度。
 */
type AnalysisPolicy = {
/**
 * 请求的分析模式
 */
mode: AnalysisMode,
/**
 * 用户请求的深度
 */
requestedDepth: AnalysisDepth,
/**
 * 实际生效的深度（可能因娱乐模式/开关而降级）
 */
effectiveDepth: AnalysisDepth,
/**
 * 最终选中的队列集合；空表示不过滤（除非 `exclude_ranked`）
 */
selectedQueueIds: number[],
/**
 * 普通模式：排除排位队列（420/440），与 allowlist 互斥使用
 */
excludeRanked: boolean,
/**
 * 队列范围
 */
queueScope: AnalysisQueueScope,
/**
 * 实际参与分析的对局数（已应用性能上限）
 */
effectiveGameCount: number,
/**
 * 只做基础统计（不做深度层）
 */
basicOnly: boolean,
/**
 * 按局决定深度（排位 deep / 娱乐 simple）
 */
perGameDepth: boolean,
/**
 * 深度结论只能来自排位对局
 */
deepConclusionsRankedOnly: boolean, enableTimeline: boolean, enableOpponent: boolean, enableTeammate: boolean, enableSelfImprovement: boolean,
/**
 * 本地 AI 是否具备可用前提（仍需运行期存在排位深度证据）
 */
localAiEligible: boolean,
/**
 * 降级诊断
 */
diagnostics: Array<AnalysisDiagnostic>, };

// --- 从 AnalysisQueueScope.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 队列范围（由最终选中的队列集合推导）
 */
type AnalysisQueueScope = "unfiltered" | "rankedOnly" | "nonRankedOnly" | "mixed";

// --- 从 BanInfo.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type BanInfo = { championId: number | null, pickTurn: number | null, };

// --- 从 ChampSelectAction.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type ChampSelectAction = { actorCellId: number | null, championId: number | null, completed: boolean, id: number, isAllyAction: boolean | null, isInProgress: boolean | null, pickTurn: number | null, type: string, isCurrentUser: boolean | null, };

// --- 从 ChampSelectBans.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type ChampSelectBans = { myTeamBans: Array<number | null>, theirTeamBans: Array<number | null>, };

// --- 从 ChampSelectPlayer.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type ChampSelectPlayer = { cellId: number, puuid: string | null, summonerId: string | null, championId: number | null, championPickIntent: number | null, selectedSkinId: number | null, spell1Id: number | null, spell2Id: number | null, assignedPosition: string | null, displayName: string | null, tagLine: string | null, profileIconId: bigint | null, tier: string | null, recentMatches: Array<SimpleMatchInfo> | null, };

// --- 从 ChampSelectSession.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type ChampSelectSession = { localPlayerCellId: number, myTeam: Array<ChampSelectPlayer>, theirTeam: Array<ChampSelectPlayer>, bans: ChampSelectBans, timer: ChampSelectTimer, actions: Array<Array<ChampSelectAction>>, };

// --- 从 ChampSelectTimer.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type ChampSelectTimer = { phase: string, };

// --- 从 ChampionStat.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 英雄统计数据
 */
type ChampionStat = {
/**
 * 英雄ID
 */
championId: number,
/**
 * 英雄名称（可选）
 */
championName: string | null,
/**
 * 使用场次
 */
games: number,
/**
 * 胜场
 */
wins: number,
/**
 * 胜率
 */
winRate: number,
/**
 * 平均KDA
 */
avgKda: number, };

// --- 从 ConnectionInfo.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type ConnectionInfo = { state: ConnectionState, consecutive_failures: number, error_message: string | null, };

// --- 从 ConnectionState.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type ConnectionState = "Connected" | "ProcessFound" | "Unstable" | "AuthExpired" | "Disconnected";

// --- 从 DataDragonRune.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type DataDragonRune = { id: bigint, name: string, icon: string, short_desc: string, long_desc: string, };

// --- 从 DeathBreakdownCard.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type DeathBreakdownCard = { totalDeaths: number, solo: number, gankOrMulti: number, towerOrMinion: number, soloRate: number, gankRate: number, summary: string, };

// --- 从 DeathCause.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 阵亡原因（过程复盘）
 */
type DeathCause = "solo" | "gankOrMulti" | "towerOrMinion";

// --- 从 DeterministicAdvice.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 确定性建议
 *
 * 只在对应特征「可下结论」时产生，因此必然带着样本量与证据对局。
 */
type DeterministicAdvice = {
/**
 * 与来源特征相同的稳定标识
 */
key: string, title: string, problem: string,
/**
 * 可核对的证据描述（含具体数值与样本量）
 */
evidence: string, suggestions: Array<string>, priority: number, category: AdviceCategory, perspective: AdvicePerspective, sampleCount: number, confidence: EvidenceConfidence, evidenceGameIds: number[], position?: string, targetPlayer?: string, };

// --- 从 DeterministicTrait.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 确定性特征
 *
 * 由特征策略产出（排位 Evidence / 娱乐 ParsedGame / 模式身份）。
 * 每条都必须能回指对局：`sample_count` / `frequency` / `confidence` / `evidence_game_ids` 必填。
 * 样本量不足时 `supports_conclusion == false`，此时只允许描述事实，不允许定性。
 */
type DeterministicTrait = {
/**
 * 稳定标识（前端本地化 / 分组的键）
 */
key: string, name: string, description: string, sentiment: TraitSentiment,
/**
 * 参与该特征计算的对局数
 */
sampleCount: number,
/**
 * 样本中符合该结论的占比，取值 `0.0..=1.0`
 */
frequency: number, confidence: EvidenceConfidence,
/**
 * 样本量是否足以支撑结论
 */
supportsConclusion: boolean,
/**
 * 支撑该特征的对局 ID（升序）
 */
evidenceGameIds: number[],
/**
 * 位置维度（`None` 表示全局）
 */
position?: string, };

// --- 从 EventEvidence.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 事件证据（击杀 / 死亡 / 助攻 / 资源 / 建筑 / 视野 / 出装 / 加点…）
 */
type EventEvidence = { kills: number, deaths: number, assists: number, deathsSolo: number, deathsGankOrMulti: number, deathsTowerOrMinion: number,
/**
 * 参与（击杀或助攻）的小龙数
 */
dragonTakedowns: number, heraldTakedowns: number, baronTakedowns: number, hordeTakedowns: number,
/**
 * 地图上出现的小龙次数（含未参与）
 */
dragonsSeen: number, heraldsSeen: number, baronsSeen: number,
/**
 * 敌方拿龙且自己未参与
 */
dragonsMissed: number, heraldsMissed: number, baronsMissed: number,
/**
 * 建筑击杀 + 建筑助攻
 */
buildingTakedowns: number, buildingsSeen: number, turretPlates: number, wardsPlaced: number, wardsKilled: number, itemsPurchased: number, itemsSold: number, itemsDestroyed: number, itemsUndo: number, skillLevelUps: number, levelUps: number, specialKills: number, dragonSouls: number,
/**
 * 按时间升序的关键事件（抽全）
 */
keyEvents: Array<KeyEventEvidence>,
/**
 * 未知 type 聚合（不丢弃）
 */
unknownEvents: Array<UnknownTimelineEvent>, };

// --- 从 EventInvolvement.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 目标玩家在事件中的角色
 */
type EventInvolvement = "killer" | "victim" | "assist" | "uninvolved" | "actor";

// --- 从 EvidenceBundle.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 多局证据包
 */
type EvidenceBundle = { targetPuuid: string, matchCount: number, matches: Array<MatchEvidence>,
/**
 * 按 (queue_id 升序, position 升序) 排列
 */
summaries: Array<EvidenceSummary>, diagnostics: Array<EvidenceDiagnostic>, };

// --- 从 EvidenceConfidence.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 样本量置信度（禁止一场触发全局强结论）
 */
type EvidenceConfidence = "insufficient" | "low" | "medium" | "high";

// --- 从 EvidenceDiagnostic.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 证据诊断（向用户解释「为什么这条结论不可用」）
 */
type EvidenceDiagnostic = { code: EvidenceIssue, message: string, };

// --- 从 EvidenceEventKind.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 关键事件类型（抽取层覆盖时间线已知枚举；未知进 Unknown）
 */
type EvidenceEventKind = "championKill" | "championDeath" | "championAssist" | "championSpecialKill" | "dragon" | "herald" | "baron" | "horde" | "eliteMonster" | "building" | "turretPlate" | "wardPlaced" | "wardKill" | "itemPurchased" | "itemSold" | "itemDestroyed" | "itemUndo" | "skillLevelUp" | "levelUp" | "dragonSoul" | "gameEnd" | "pauseEnd" | "unknown";

// --- 从 EvidenceEventRates.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 事件频率（场均）
 */
type EvidenceEventRates = {
/**
 * 有事件证据（即有时间线）的对局数
 */
sampleSize: number, killsPerGame: number, deathsPerGame: number, assistsPerGame: number, dragonTakedownsPerGame: number, heraldTakedownsPerGame: number, baronTakedownsPerGame: number, hordeTakedownsPerGame: number, buildingTakedownsPerGame: number,
/**
 * 至少参与一条小龙的对局占比
 */
gamesWithDragonRate: number,
/**
 * 至少参与一次大龙的对局占比
 */
gamesWithBaronRate: number, };

// --- 从 EvidenceIssue.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 证据缺陷码
 */
type EvidenceIssue = "timelineMissing" | "timelineFramesMissing" | "timelineFramesEmpty" | "targetParticipantFramesMissing" | "singleFrameNoRate" | "opponentUnidentified" | "opponentFromSpatialProximity" | "matchSkipped";

// --- 从 EvidencePosition.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 统一位置
 *
 * 声明顺序即排序顺序，聚合输出依赖它保持确定性。
 */
type EvidencePosition = "TOP" | "JUNGLE" | "MID" | "ADC" | "SUPPORT" | "ARAM" | "FLEX" | "UNKNOWN";

// --- 从 EvidenceQuality.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 单局证据的完整度
 */
type EvidenceQuality = "full" | "timelineMissing" | "timelinePartial";

// --- 从 EvidenceSummary.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 按 (队列, 位置) 聚合的证据摘要
 */
type EvidenceSummary = { queueId: number, position: EvidencePosition, sampleSize: number, wins: number,
/**
 * 胜率**百分比**，取值 `0.0..=100.0`（55% 是 `55.0`，不是 `0.55`）。
 *
 * 定义为 `wins / sample_size * 100`；`sample_size == 0` 时为 `0.0`。
 * 同结构里的 `event_rates` 用的是 0-1 占比，两者刻意不同，前端别混用。
 */
winRate: number, confidence: EvidenceConfidence,
/**
 * 样本量是否足以支撑结论
 */
supportsConclusion: boolean,
/**
 * 识别到对线对手的对局数
 */
opponentIdentifiedGames: number, phaseAverages: Array<PhaseAverages>, eventRates: EvidenceEventRates,
/**
 * 支撑该摘要的对局 ID（升序去重）
 */
evidenceGameIds: number[], };

// --- 从 GameAdvice.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 游戏建议（v3.0 新增）⭐
 */
type GameAdvice = { title: string, problem: string, evidence: string, suggestions: Array<string>, priority: number, category: AdviceCategory, perspective: AdvicePerspective, affectedRole: string | null, targetPlayer: string | null, };

// --- 从 GameDetail.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type GameDetail = { gameId: number, gameDuration: number, gameCreation: number, gameMode: string, gameType: string, gameVersion: string, mapId: number, queueId: number, teams: Array<TeamInfo>, participants: Array<ParticipantInfo>, blueTeamStats: TeamStats, redTeamStats: TeamStats, bestPlayerChampionId: number, maxDamage: number, maxTankChampionId: number, maxTank: number, maxStreakChampionId: number, maxStreak: number, };

// --- 从 GamePhase.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 对局阶段
 */
type GamePhase = "early" | "mid" | "late";

// --- 从 GameProcessReview.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 单局过程复盘（详情弹窗）
 */
type GameProcessReview = { insight: ProcessInsight, keyMoments: Array<ProcessKeyMoment>, opponentCompare: OpponentCompareCard | null,
/**
 * full / timelineMissing / timelinePartial（与 EvidenceQuality 同形字符串）
 */
quality: string,
/**
 * 是否命中前端传入的已分析证据（未再打 LCU）
 */
fromCache: boolean, };

// --- 从 HextechAugmentStat.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 增强条目（英雄侧统计）
 */
type HextechAugmentStat = { id: number, name: string, rarity: number, rarityName: string, rarityDisplayName: string, iconUrl: string, winRate: number, pickRate: number, games: number | null, wins: number | null, tier: number | null, rank: number | null, };

// --- 从 HextechAugmentTrio.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 推荐增强三连
 */
type HextechAugmentTrio = { augmentIds: Array<number>, winRate: number, pickRate: number, games: number | null, wins: number | null, };

// --- 从 HextechChampionDetail.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 海克斯英雄详情（增强 + 出装）
 */
type HextechChampionDetail = { summary: HextechChampionSummary, augments: Array<HextechAugmentStat>, augmentTrios: Array<HextechAugmentTrio>, summonerSpells: Array<HextechSpellCombo>, skillOrders: Array<HextechSkillOrder>, startingItems: Array<HextechItemCombo>, coreItems: Array<HextechItemCombo>, };

// --- 从 HextechChampionSummary.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 海克斯英雄摘要
 */
type HextechChampionSummary = { championId: number, name: string, alias: string, title: string, iconUrl: string, roles: Array<string>, winRate: number, pickRate: number, tier: number | null, dataVersion: string, gamePatch: string | null, };

// --- 从 HextechItemCombo.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 装备组合
 */
type HextechItemCombo = { itemIds: Array<number>, winRate: number, pickRate: number, games: number, wins: number, };

// --- 从 HextechSkillOrder.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 技能加点
 */
type HextechSkillOrder = { skillKeys: Array<string>, skillOrder: Array<number>, winRate: number, pickRate: number, games: number, wins: number, };

// --- 从 HextechSpellCombo.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 召唤师技能组合
 */
type HextechSpellCombo = { spellIds: Array<number>, winRate: number, pickRate: number, games: number, wins: number, };

// --- 从 HextechTierList.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 强度榜
 */
type HextechTierList = { dataVersion: string, gamePatch: string | null, region: string, data: Array<HextechTierListItem>, };

// --- 从 HextechTierListItem.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 强度榜行
 */
type HextechTierListItem = { championId: number, name: string, alias: string, iconUrl: string, roles: Array<string>, winRate: number, pickRate: number, tier: number | null, rank: number, };

// --- 从 KeyEventEvidence.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 单条关键事件证据（保留时间戳，供上层引用为证据）
 */
type KeyEventEvidence = { kind: EvidenceEventKind, timestampMs: number, involvement: EventInvolvement,
/**
 * 事件补充信息（龙的子类型 / 建筑类型 / 未知 raw type 等）
 */
detail?: string, deathCause?: DeathCause, killerParticipantId?: number, assistantCount: number,
/**
 * 击杀者是否为对线对手（仅死亡事件）
 */
laneOpponentKill: boolean,
/**
 * 目标玩家在事件邻近帧的粗活动（「我在干嘛」）
 */
activityContext?: ActivityContext,
/**
 * 对位玩家在事件邻近帧的粗活动（「对位在干嘛」）
 */
opponentActivityContext?: ActivityContext, itemId?: number, skillSlot?: number, actorParticipantId?: number, positionX?: number, positionY?: number, bounty?: number, killStreakLength?: number, killerTeamId?: number,
/**
 * 资源/建筑是否己方阵营击杀
 */
alliedSide?: boolean,
/**
 * victimDamageReceived 条目数（有则保留，供后续伤害复盘）
 */
victimDamageReceivedCount?: number, };

// --- 从 LaningProcessCard.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type LaningProcessCard = { sampleSize: number, avgCsDiff: number, avgGoldDiff: number, avgOverallAdvantagePct: number, summary: string, };

// --- 从 LiveClientPlayer.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type LiveClientPlayer = { summonerName: string, championName: string, isBot: boolean, isDead: boolean, items: any[], level: number, position: string, rawChampionName: string, respawnTimer: number, runes: any, scores: any, skinID: number, summonerSpells: any, team: string, };

// --- 从 LobbyInfo.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type LobbyInfo = { canStartActivity: boolean, gameConfig: any, invitations: any[], localMember: LobbyMember | null, members: Array<LobbyMember>, mucJwtDto: any, multiUserChatId: string, multiUserChatPassword: string, partyId: string, partyType: string, restrictions: any[], warnings: any[], };

// --- 从 LobbyMember.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type LobbyMember = { summonerId: string, displayName: string, puuid: string, summonerName: string, summonerLevel: number, summonerIconId: number, isBot: boolean, isLeader: boolean, isSpectator: boolean, ready: boolean, botChampionId: number, botDifficulty: string, botId: string, botPosition: string, firstPositionPreference: string, secondPositionPreference: string, allowedChangeActivity: boolean, allowedInviteOthers: boolean, allowedKickOthers: boolean, allowedStartActivity: boolean, };

// --- 从 LowPriorityData.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type LowPriorityData = { bustedLeaverAccessToken: string, penalizedSummonerIds: number[], penaltyTime: number, penaltyTimeRemaining: number, reason: string, };

// --- 从 MatchAnalysisRequest.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 统一对局分析请求
 */
type MatchAnalysisRequest = {
/**
 * 期望拉取的对局数量
 */
count: number,
/**
 * 分析模式（决定默认队列过滤）
 */
mode: AnalysisMode,
/**
 * 用户请求的分析深度
 */
depth: AnalysisDepth,
/**
 * 单队列覆盖（优先级低于 `queue_ids`）
 */
queueId?: number,
/**
 * 多队列覆盖；`Some(vec![])` 表示显式不过滤
 */
queueIds?: number[],
/**
 * 功能开关
 */
features: AnalysisFeatureFlags,
/**
 * 性能上限：实际参与分析的最大对局数
 */
maxAnalysisGames?: number,
/**
 * 建议视角（自我改进 / 针对对手 / 协作队友）
 */
perspective?: AdvicePerspective,
/**
 * 建议措辞里的目标玩家名（针对对手 / 协作队友时使用）
 */
targetPlayer?: string, };

// --- 从 MatchAnalysisResult.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 统一对局分析结果
 *
 * 统计部分直接复用现有结构，避免重复定义。
 */
type MatchAnalysisResult = {
/**
 * 总览统计（所有参与分析的对局合计；全部模式下为混合合计，供列表/兼容）
 */
overallStats: PlayerMatchStats,
/**
 * 排位桶统计（420/440）；无排位样本时为 None
 */
rankedStats?: PlayerMatchStats,
/**
 * 非排位桶统计（匹配/乱斗/娱乐等）；无样本时为 None
 */
otherStats?: PlayerMatchStats,
/**
 * 分位置统计
 */
positionStats: Array<PositionStats>,
/**
 * 主要位置
 */
mainPosition: string,
/**
 * 深度证据覆盖的对局数（受 `maxAnalysisGames` 约束）
 */
analyzedGames: number,
/**
 * 展示与基础统计覆盖的对局数（受 `count` 约束，**不**受 `maxAnalysisGames` 影响）
 */
displayGames: number,
/**
 * 展示用战绩列表（与 `overall_stats.recent_performance` 同一批对局）
 *
 * 有了它，前端一次调用就能同时渲染战绩列表与统计，不需要第二个命令。
 */
matches: Array<MatchPerformance>,
/**
 * 确定性特征（唯一来源是 `evidence`）
 */
traits: Array<DeterministicTrait>,
/**
 * 确定性建议（唯一来源是 `evidence`）
 */
advice: Array<DeterministicAdvice>,
/**
 * 生效策略（便于前端解释结论来源）
 */
policy: AnalysisPolicy,
/**
 * 能力声明
 */
capabilities: AnalysisCapabilities,
/**
 * 降级诊断（策略级 + 运行期）
 */
diagnostics: Array<AnalysisDiagnostic>,
/**
 * 确定性证据包（时间线 / 位置 / 对手 / 事件 / 聚合）
 *
 * 由 `domains::analysis::evidence` 产出；`None` 表示本次分析没有可用证据。
 */
evidence?: EvidenceBundle,
/**
 * 本地 BYOK AI 解读（显式触发后由前端写回；编排器本身不调用 AI）
 */
aiInsight?: AiInsight, };

// --- 从 MatchEvidence.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 单局证据
 */
type MatchEvidence = { gameId: number, queueId: number, gameDurationSeconds: number, gameCreation: number, participantId: number, teamId: number, championId: number, win: boolean, position: EvidencePosition, quality: EvidenceQuality, opponent?: OpponentEvidence,
/**
 * 只包含真实存在的阶段（短局 / remake 可能只有 early）
 */
phases: Array<PhaseEvidence>, events?: EventEvidence, timelineSpan?: TimelineSpan, diagnostics: Array<EvidenceDiagnostic>, };

// --- 从 MatchInfo.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type MatchInfo = { matchId: string, players: Array<PlayerInfo>, };

// --- 从 MatchPerformance.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 单场比赛表现
 */
type MatchPerformance = { gameId: number | undefined, win: boolean, championId: number, championName: string, kills: number, deaths: number, assists: number, kda: number,
/**
 * 自研单场评级：S+ / S / A / B / C / D（由 KDA 阈值映射，非官方）
 */
grade: string, gameDuration: number | null, gameCreation: number | undefined, queueId: number | undefined, gameMode: string | null, role: string, lane: string,
/**
 * ASCII 位置码：TOP / JUNGLE / MID / ADC / SUPPORT / ARAM / FLEX / UNKNOWN
 */
position: string, };

// --- 从 MatchmakingError.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type MatchmakingError = { errorType: string, id: number, message: string, penalizedSummonerId: number, penaltyTimeRemaining: number, };

// --- 从 MatchmakingState.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type MatchmakingState = { errors: Array<MatchmakingError>, lowPriorityData: LowPriorityData, searchState: string, estimatedQueueTime: number | null, };

// --- 从 MultiPositionAnalysis.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ⭐ v3.4: 多位置分组分析结果
 */
type MultiPositionAnalysis = {
/**
 * 所有位置的统计（按场次从多到少排序）
 */
positionStats: Array<PositionStats>,
/**
 * 主要位置（场次最多的）
 */
mainPosition: string,
/**
 * 总览数据（所有位置合计；全部模式下为混合合计）
 */
overallStats: PlayerMatchStats,
/**
 * 排位桶统计（420/440）
 */
rankedStats?: PlayerMatchStats,
/**
 * 非排位桶统计
 */
otherStats?: PlayerMatchStats, };

// --- 从 ObjectiveProcessCard.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type ObjectiveProcessCard = { dragonsSeen: number, dragonsTaken: number, dragonsMissed: number, heraldsSeen: number, heraldsTaken: number, heraldsMissed: number, baronsSeen: number, baronsTaken: number, baronsMissed: number, missedActivity: Array<ActivityBucketCount>, summary: string, };

// --- 从 OpggChampionBuild.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * OP.GG 英雄详细数据
 */
type OpggChampionBuild = { summary: OpggChampionSummary, summonerSpells: Array<OpggSummonerSpell>, championSkills: OpggSkills, items: OpggItems, counters: OpggCounters, perks: Array<OpggPerk>, };

// --- 从 OpggChampionSummary.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 英雄摘要信息
 */
type OpggChampionSummary = { name: string, championId: number, icon: string, position: string, winRate: number | null, pickRate: number | null, banRate: number | null, kda: number | null, tier: string | null, rank: number | null, };

// --- 从 OpggCounter.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 克制英雄
 */
type OpggCounter = { championId: number, winRate: number, };

// --- 从 OpggCounters.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 克制关系
 */
type OpggCounters = { strongAgainst: Array<OpggCounter>, weakAgainst: Array<OpggCounter>, };

// --- 从 OpggItem.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 装备项目
 */
type OpggItem = { id: number, ids: Array<number>, icons: Array<string>, win: number, play: number, pickRate: number, };

// --- 从 OpggItems.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 装备数据
 */
type OpggItems = { startItems: Array<OpggItem>, coreItems: Array<OpggItem>, boots: Array<OpggItem>, lastItems: Array<OpggItem>, };

// --- 从 OpggPerk.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 符文配置
 */
type OpggPerk = { primaryId: number, secondaryId: number, perks: Array<number>, win: number, play: number, pickRate: number, };

// --- 从 OpggSkills.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 英雄技能
 */
type OpggSkills = { masteries: Array<string>, order: Array<string>, play: number, win: number, pickRate: number, };

// --- 从 OpggSummonerSpell.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 召唤师技能
 */
type OpggSummonerSpell = { spellId: number, ids: Array<number>, win: number, play: number, pickRate: number, };

// --- 从 OpggTierCounter.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 强度榜对抗样本
 */
type OpggTierCounter = { championId: number, play: number, win: number, };

// --- 从 OpggTierList.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 层级列表
 */
type OpggTierList = { meta: OpggTierListMeta, data: Array<OpggTierListItem>, };

// --- 从 OpggTierListItem.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 层级列表项（对齐现网 lol-api-champion 结构）
 */
type OpggTierListItem = { championId: number, averageStats: OpggTierStats,
/**
 * 排位有分路；ARAM/URF/Arena 为空
 */
positions: Array<OpggTierPosition>,
/**
 * ARAM 常见；其它模式多为空
 */
roles: Array<OpggTierRole>, };

// --- 从 OpggTierListMeta.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 层级列表元数据
 */
type OpggTierListMeta = { version: string, region: string, mode: string, tier: string, };

// --- 从 OpggTierPosition.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 强度榜分路行
 */
type OpggTierPosition = { name: string, stats: OpggTierStats, counters: Array<OpggTierCounter>, };

// --- 从 OpggTierRole.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ARAM 等模式的英雄定位占比
 */
type OpggTierRole = { name: string, winRate: number, roleRate: number, play: number, };

// --- 从 OpggTierStats.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 强度榜统计（全英雄或某分路）
 */
type OpggTierStats = { play: number,
/**
 * 排位/ARAM/URF: 胜率；Arena: 吃鸡率（first_place / play）
 */
winRate: number, pickRate: number,
/**
 * ARAM/URF 常为 0（现网 null）
 */
banRate: number, kda: number,
/**
 * OP.GG tier 数字（1=OP …）
 */
tier: number, rank: number,
/**
 * Arena: 吃鸡场次
 */
firstPlace: number | null,
/**
 * Arena: 排名总和
 */
totalPlace: number | null, };

// --- 从 OpponentCompareCard.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 单局对位对比
 */
type OpponentCompareCard = { myChampionId: number, opponentChampionId: number | null, opponentParticipantId: number,
/**
 * TOP / JUNGLE / ...
 */
position: string, confidence: number, phases: Array<OpponentPhaseCompare>, summary: string | null, };

// --- 从 OpponentEvidence.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 对线对手证据
 */
type OpponentEvidence = { participantId: number, teamId: number, championId?: number, position: EvidencePosition, method: OpponentMatchMethod,
/**
 * 0.0 ~ 1.0
 */
confidence: number, };

// --- 从 OpponentMatchMethod.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 对手识别方式
 */
type OpponentMatchMethod = "laneRole" | "positionMatch" | "spatialProximity";

// --- 从 OpponentPhaseCompare.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 对位阶段差（相对对手，正数=领先）
 */
type OpponentPhaseCompare = {
/**
 * early / mid / late
 */
phase: string,
/**
 * 展示标签：前 10 分 / 10–20 分 / 20 分后
 */
label: string, csDiff: number, goldDiff: number, xpDiff: number, levelDiff: number,
/**
 * 综合优势百分比（约 [-100, 100]）
 */
overallAdvantagePct: number, myGold: number, opponentGold: number, };

// --- 从 ParticipantInfo.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type ParticipantInfo = { participantId: number, championId: number,
/**
 * 英雄中文名（含 JADE/经典模式 600xx）；详情列表展示用，避免前端目录未命中
 */
championName?: string | null, summonerName: string, profileIconId: number, teamId: number, rankTier: string | null,
/**
 * 召唤师技能 1（闪现等）
 */
spell1Id?: number | null,
/**
 * 召唤师技能 2
 */
spell2Id?: number | null,
/**
 * 主系符文树（精密 8000 / 主宰 8100 …）
 */
perkPrimaryStyle?: number | null,
/**
 * 基石符文（perk0）
 */
perk0?: number | null,
/**
 * 分路：TOP / JUNGLE / MID / ADC / SUPPORT（无法识别时省略）
 */
position?: string | null, stats: ParticipantStats, score: number | null, };

// --- 从 ParticipantStats.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type ParticipantStats = { kills: number, deaths: number, assists: number, champLevel: number, goldEarned: number, totalDamageDealtToChampions: number, totalDamageTaken: number, visionScore: number,
/**
 * 补刀（小兵）
 */
totalMinionsKilled: number,
/**
 * 野怪补刀
 */
neutralMinionsKilled: number,
/**
 * 最大多杀（2=双杀 … 5=五杀）
 */
largestMultiKill: number,
/**
 * 最大连杀
 */
largestKillingSpree: number,
/**
 * 推塔数
 */
turretKills: number,
/**
 * 推水晶数
 */
inhibitorKills: number,
/**
 * 插眼
 */
wardsPlaced: number,
/**
 * 排眼
 */
wardsKilled: number,
/**
 * 对防御塔伤害
 */
damageDealtToTurrets: number, item0: number | null, item1: number | null, item2: number | null, item3: number | null, item4: number | null, item5: number | null, item6: number | null, };

// --- 从 PhaseAverages.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 某阶段在一组对局上的均值
 */
type PhaseAverages = { phase: GamePhase,
/**
 * 有可用速率的对局数（零时长阶段不计入）
 */
sampleSize: number,
/**
 * 识别到对手且有阶段末差值的对局数
 */
opponentSampleSize: number, avgLaneCsPerMin?: number, avgJungleCsPerMin?: number, avgCsPerMin?: number, avgGoldPerMin?: number, avgXpPerMin?: number, avgCsDiff?: number, avgGoldDiff?: number, avgXpDiff?: number, avgOverallAdvantage?: number, };

// --- 从 PhaseEvidence.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 单阶段证据
 *
 * 速率的分母固定是 `(last.timestamp - first.timestamp) / 60000.0`（真实经过时间），
 * 不使用帧数量。阶段内只有一个锚点帧时速率为 `None`，绝不除零。
 */
type PhaseEvidence = { phase: GamePhase,
/**
 * 阶段内第一帧的真实时间戳
 */
startMs: number,
/**
 * 阶段内最后一帧的真实时间戳
 */
endMs: number,
/**
 * 真实经过分钟数（速率分母）
 */
durationMinutes: number,
/**
 * 落在本阶段闭区间 `[start, end]` 内的帧数，含两端边界锚点。
 *
 * 相邻阶段共享边界帧，所以边界帧会同时计入两个阶段，
 * 各阶段 `frame_count` 之和会比总帧数多（每个边界 +1）。这是刻意的：
 * 每个阶段都需要自己的起点锚点才能算出该阶段内的增量，
 * 少了它首帧的 CS/金币增量就会被算成从 0 开始。
 *
 * 因此 `frame_count` 只表示采样密度，不要拿它当速率分母 —— 速率一律用
 * `duration_minutes`，而边界帧不会被重复计入任何增量。
 */
frameCount: number,
/**
 * 阶段内线上兵线增量
 */
laneCs: number,
/**
 * 阶段内野怪增量（打野单列）
 */
jungleCs: number,
/**
 * lane + jungle
 */
totalCs: number, laneCsPerMin?: number, jungleCsPerMin?: number,
/**
 * total CS / 真实分钟
 */
csPerMin?: number, goldPerMin?: number, xpPerMin?: number, endGold: number, endXp: number, endLevel: number, opponentDiff?: PhaseOpponentDiff, };

// --- 从 PhaseOpponentDiff.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 阶段末与对手的绝对差 + 归一化优势
 *
 * `*_diff` 是阶段最后一帧的累计值绝对差，**不是** per-minute delta，两者不可混用。
 * `normalized_*` 是无量纲份额差 `(self - opponent) / (self + opponent)`，取值 [-1, 1]，
 * 只有归一化之后才允许按权重组合，禁止直接加权 raw XP/Gold。
 */
type PhaseOpponentDiff = { opponentParticipantId: number,
/**
 * total CS（线上 + 野怪）绝对差
 */
csDiff: number, goldDiff: number, xpDiff: number, levelDiff: number, normalizedCsAdvantage: number, normalizedGoldAdvantage: number, normalizedXpAdvantage: number,
/**
 * 归一化后按权重组合的总优势，[-1, 1]
 */
overallAdvantage: number, };

// --- 从 PlayerAnalysisData.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 玩家完整分析数据（包含战绩）
 */
type PlayerAnalysisData = { cellId: number, displayName: string, summonerId: string | null, puuid: string | null, isLocal: boolean, isBot: boolean, championId: number | null, championName: string | null, championPickIntent: number | null, position: string | null, tier: string | null, profileIconId: number | null, tagLine: string | null, spell1Id: bigint | null, spell2Id: bigint | null, matchStats: PlayerMatchStats | null, };

// --- 从 PlayerInfo.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type PlayerInfo = { summonerName: string, championId: number, teamId: number, };

// --- 从 PlayerMatchStats.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 玩家战绩统计（完整版 - 包含所有分析数据）
 */
type PlayerMatchStats = { totalGames: number, wins: number, losses: number, winRate: number, avgKills: number, avgDeaths: number, avgAssists: number, avgKda: number, todayGames: number, todayWins: number, dpm: number, cspm: number, vspm: number, traits: Array<SummonerTrait>, favoriteChampions: Array<AnalysisChampionStats>, recentPerformance: Array<MatchPerformance>, advice?: Array<GameAdvice>, };

// --- 从 PositionStats.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ⭐ v3.4: 单个位置的统计数据
 */
type PositionStats = {
/**
 * ASCII 位置码：TOP / JUNGLE / MID / ADC / SUPPORT / ARAM / FLEX / UNKNOWN
 */
position: string,
/**
 * 该位置的场次
 */
games: number,
/**
 * 该位置的胜场
 */
wins: number,
/**
 * 该位置的胜率
 */
winRate: number,
/**
 * 该位置的统计数据
 */
stats: PlayerMatchStats,
/**
 * 英雄池数据（Top 5）
 */
championPool: Array<ChampionStat> | null,
/**
 * 胜率趋势（最近的对局）
 */
winRateTrend: Array<TrendPoint> | null,
/**
 * 过程复盘洞察（深度时间线）；无时间线时带降级说明
 */
processInsight: ProcessInsight | null, };

// --- 从 ProcessAction.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type ProcessAction = { key: string, title: string, detail: string, priority: number, };

// --- 从 ProcessInsight.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 过程复盘洞察（不以胜率为主结论）
 */
type ProcessInsight = { sampleSize: number, timelineGames: number, hasTimeline: boolean, degradationMessage: string | null, deathBreakdown: DeathBreakdownCard | null, laningProcess: LaningProcessCard | null, objectiveProcess: ObjectiveProcessCard | null, visionProcess: VisionProcessCard | null, actions: Array<ProcessAction>, };

// --- 从 ProcessKeyMoment.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 单局过程复盘的关键时刻（短列表，不是完整时间轴）
 */
type ProcessKeyMoment = { timestampMs: number, label: string,
/**
 * 我在干嘛（邻近帧粗分类）
 */
detail: string | null,
/**
 * 对位在干嘛
 */
opponentDetail: string | null, };

// --- 从 QueueStats.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type QueueStats = { tier: string, division: string, leaguePoints: number, wins: number, losses: number, };

// --- 从 RankInfo.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type RankInfo = { soloTier: string | null, soloDivision: string | null, soloLp: number | null, soloWins: number | null, soloLosses: number | null, flexTier: string | null, flexDivision: string | null, flexLp: number | null, flexWins: number | null, flexLosses: number | null, };

// --- 从 RankedStats.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type RankedStats = { queueMap: { [key in string]?: QueueStats }, };

// --- 从 RecentGame.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 最近游戏信息
 */
type RecentGame = { gameId: number, championId: number, gameMode: string, win: boolean, kills: number, deaths: number, assists: number, gameDuration: number, gameCreation: number, queueId: number, performanceRating: string, };

// --- 从 RunePage.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 符文页面数据结构
 */
type RunePage = { id: bigint, name: string, current: boolean, isEditable: boolean, isDeletable: boolean, isValid: boolean, primaryStyleId: number, subStyleId: number, selectedPerkIds: Array<number>, };

// --- 从 RunePages.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type RunePages = { pages: Array<DataDragonRune>, };

// --- 从 SimpleMatchInfo.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 简单对局信息
 */
type SimpleMatchInfo = { gameId: number, championId: number, win: boolean, kills: number, deaths: number, assists: number, gameCreation: number, };

// --- 从 StaticCatalogMeta.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type StaticCatalogMeta = { version: string,
/**
 * Unix 毫秒（JSON IPC 为 JS number，不是 bigint）
 */
loadedAt: number,
/**
 * `disk` | `network` | `disk-offline` | `disk-stale`
 */
source: string, };

// --- 从 SummonerInfo.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type SummonerInfo = { displayName: string, gameName: string | null, tagLine: string | null, summonerLevel: number, profileIconId: number, puuid: string, accountId: string, summonerId: string, xpSinceLastLevel: number, xpUntilNextLevel: number, percentCompleteForNextLevel: number | null, gameStatus: string | null, availability: string | null, challengePoints: string | null, challengeCrystalLevel: string | null, soloRankTier: string | null, soloRankDivision: string | null, soloRankWins: number | null, soloRankLosses: number | null, soloRankLp: number | null, flexRankTier: string | null, flexRankDivision: string | null, flexRankWins: number | null, flexRankLosses: number | null, flexRankLp: number | null, highestRankThisSeason: string | null, currentPerkPage: string | null, primaryStyleId: number | null, subStyleId: number | null, selectedPerkIds: Array<number> | null, };

// --- 从 SummonerSpellInfo.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 召唤师技能信息结构
 */
type SummonerSpellInfo = { id: number, name: string, description: string, summonerLevel: number, cooldown: number, gameModes: Array<string>, iconPath: string, };

// --- 从 SummonerTrait.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 召唤师特征标签
 */
type SummonerTrait = { name: string, description: string, score: number, type: string, };

// --- 从 SummonerWithMatches.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type SummonerWithMatches = { displayName: string, summonerInfo: SummonerInfo, matches: PlayerMatchStats,
/**
 * 与 `matches` 同源的一次 analyze 结果投影，避免搜索页再打第二轮 LCU
 */
positionAnalysis?: MultiPositionAnalysis, };

// --- 从 TeamAnalysisData.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 队伍分析数据
 */
type TeamAnalysisData = { myTeam: Array<PlayerAnalysisData>, enemyTeam: Array<PlayerAnalysisData>, localPlayerCellId: number, gamePhase: string, queueId: number, isCustomGame: boolean, actions: Array<Array<ChampSelectAction>> | null, bans: ChampSelectBans | null, timer: ChampSelectTimer | null, };

// --- 从 TeamInfo.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type TeamInfo = { teamId: number | null, win: string | null, bans: Array<BanInfo>, baronKills: number | null, dragonKills: number | null, towerKills: number | null, inhibitorKills: number | null,
/**
 * 峡谷先锋击杀数（LCU 常见字段）
 */
riftHeraldKills: number | null,
/**
 * 虚空幼体击杀数（较新版本）
 */
hordeKills: number | null, firstBlood: boolean | null, firstTower: boolean | null,
/**
 * 部分 LCU 版本误拼为 firstDargon
 */
firstDragon: boolean | null, firstBaron: boolean | null, firstInhibitor: boolean | null, firstRiftHerald: boolean | null, };

// --- 从 TeamStats.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type TeamStats = { kills: number, goldEarned: number, totalDamageDealtToChampions: number, visionScore: number, };

// --- 从 TimelineSpan.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 时间线覆盖范围
 */
type TimelineSpan = { startMs: number, endMs: number, frameCount: number,
/**
 * 其中包含目标玩家 participantFrame 的帧数
 */
targetFrameCount: number, };

// --- 从 TraitSentiment.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 特征倾向
 */
type TraitSentiment = "good" | "bad" | "neutral";

// --- 从 TrendPoint.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 趋势点数据
 */
type TrendPoint = {
/**
 * 对局索引（第几场）
 */
index: number,
/**
 * 是否胜利
 */
win: boolean,
/**
 * 累计胜率（截止到这场）
 */
cumulativeWinRate: number,
/**
 * 移动平均胜率（最近5场）
 */
movingAvgWinRate: number, };

// --- 从 UnknownTimelineEvent.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 未知事件样例（禁止静默丢弃）
 */
type UnknownTimelineEvent = { rawType: string, timestampMs: number, count: number, };

// --- 从 VisionProcessCard.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type VisionProcessCard = { wardsPlaced: number, wardsKilled: number, gamesWithWards: number, summary: string, };
