/**
 * 全局类型声明 - 由 scripts/sync-types.mjs 自动生成
 *
 * ************************************************
 * *                                               *
 * *           !!!   请勿手动修改此文件   !!!            *
 * *                                               *
 * *************************************************
 *
 * 如需更新，请运行 'odescripts/sync-types.mjs'
 */

// --- 从 AnalysisChampionStats.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 分析用英雄统计数据（包含英雄名称）
 */
type AnalysisChampionStats = { championId: number, championName: string, games: number, wins: number, winRate: number, };


// --- 从 BanInfo.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type BanInfo = { championId: number | null, pickTurn: number | null, };


// --- 从 Builds.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type Builds = { builds: Array<BuildSection>, };


// --- 从 BuildSection.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type BuildSection = { title: string, item_ids: Array<string>, };


// --- 从 ChampionContent.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type ChampionContent = { alias: string, id: string, index: number | null, name: string, position: string, version: string, winRate: string | null, pickCount: number | null, timestamp: bigint | null, officialVersion: string | null, itemBuilds: Array<ItemBuild> | null, runes: Array<RuneSet> | null, skills: Array<string> | null, };


// --- 从 ChampionDataResponse.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type ChampionDataResponse = { id: number | null, source: string | null, version: string | null, championAlias: string | null, championId: string | null, content: Array<ChampionContent>, };


// --- 从 ChampionItemBlock.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type ChampionItemBlock = { type: string | null, items: Array<ItemInfo> | null, };


// --- 从 ChampionStats.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 英雄统计信息
 */
type ChampionStats = { championId: number, gamesPlayed: number, wins: number, winRate: number, };


// --- 从 ChampSelectAction.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type ChampSelectAction = { actorCellId: number | null, championId: number | null, completed: boolean, id: number, isAllyAction: boolean | null, isInProgress: boolean | null, pickTurn: number | null, type: string, isCurrentUser: boolean | null, };


// --- 从 ChampSelectBans.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type ChampSelectBans = { myTeamBans: Array<number | null>, theirTeamBans: Array<number | null>, };


// --- 从 ChampSelectPlayer.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type ChampSelectPlayer = { cellId: number, puuid: string | null, summonerId: string | null, championId: number | null, championPickIntent: number | null, selectedSkinId: number | null, spell1Id: number | null, spell2Id: number | null, assignedPosition: string | null, displayName: string | null, tagLine: string | null, profileIconId: bigint | null, tier: string | null, recentMatches: Array<SimpleMatchInfo> | null, };


// --- 从 ChampSelectPlayerInfo.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type ChampSelectPlayerInfo = { summonerId: string, displayName: string, tagLine: string | null, profileIconId: bigint, tier: string | null, puuid: string, recentMatches: Array<SimpleMatchInfo>, };


// --- 从 ChampSelectSession.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type ChampSelectSession = { localPlayerCellId: number, myTeam: Array<ChampSelectPlayer>, theirTeam: Array<ChampSelectPlayer>, bans: ChampSelectBans, timer: ChampSelectTimer, actions: Array<Array<ChampSelectAction>>, };


// --- 从 ChampSelectTeamInfo.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type ChampSelectTeamInfo = { myTeam: Array<ChampSelectPlayerInfo>, theirTeam: Array<ChampSelectPlayerInfo>, };


// --- 从 ChampSelectTimer.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type ChampSelectTimer = { phase: string, };


// --- 从 ConnectionInfo.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type ConnectionInfo = { state: ConnectionState, consecutive_failures: number, error_message: string | null, };


// --- 从 ConnectionState.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type ConnectionState = "Connected" | "ProcessFound" | "Unstable" | "AuthExpired" | "Disconnected";


// --- 从 CurrentChampion.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 当前选择的英雄信息
 */
type CurrentChampion = { 
/**
 * 英雄ID
 */
championId: number, 
/**
 * 英雄名称
 */
championName: string, 
/**
 * 是否已选择
 */
isPicked: boolean, };


// --- 从 DataDragonRune.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type DataDragonRune = { id: bigint, name: string, icon: string, short_desc: string, long_desc: string, };


// --- 从 GameAdvice.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 游戏建议（v3.0 新增）⭐
 */
type GameAdvice = { title: string, problem: string, evidence: string, suggestions: Array<string>, priority: number, category: AdviceCategory, perspective: AdvicePerspective, affectedRole: string | null, targetPlayer: string | null, };


// --- 从 GameDetail.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type GameDetail = { gameId: number, gameDuration: number, gameCreation: number, gameMode: string, gameType: string, gameVersion: string, mapId: number, queueId: number, teams: Array<TeamInfo>, participants: Array<ParticipantInfo>, blueTeamStats: TeamStats, redTeamStats: TeamStats, bestPlayerChampionId: number, maxDamage: number, maxTankChampionId: number, maxTank: number, maxStreakChampionId: number, maxStreak: number, };


// --- 从 GameflowPhase.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type GameflowPhase = { phase: string, };


// --- 从 ItemBlock.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 装备推荐块数据结构
 */
type ItemBlock = { type: string, items: Array<RecommendedItem>, };


// --- 从 ItemBuild.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type ItemBuild = { title: string, map: string | null, mode: string | null, type: string | null, sortrank: number | null, startedFrom: string | null, associatedChampions: Array<number> | null, associatedMaps: Array<number> | null, blocks: Array<ChampionItemBlock> | null, };


// --- 从 ItemInfo.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type ItemInfo = { id: string, count: number | null, };


// --- 从 ItemSet.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 装备推荐套装数据结构
 */
type ItemSet = { title: string, champion: string, mode: string, map: string, blocks: Array<ItemBlock>, };


// --- 从 LcuAuthInfo.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type LcuAuthInfo = { appPort: number, remotingAuthToken: string, riotclientAppPort: number, riotclientAuthToken: string, };


// --- 从 LcuWebSocketEvent.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * LCU WebSocket 事件
 */
type LcuWebSocketEvent<T> = { eventType: string, data: T, };


// --- 从 LiveClientPlayer.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type LiveClientPlayer = { summonerName: string, championName: string, isBot: boolean, isDead: boolean, items: any[], level: number, position: string, rawChampionName: string, respawnTimer: number, runes: any, scores: any, skinID: number, summonerSpells: any, team: string, };


// --- 从 LobbyInfo.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type LobbyInfo = { canStartActivity: boolean, gameConfig: any, invitations: any[], localMember: LobbyMember | null, members: Array<LobbyMember>, mucJwtDto: any, multiUserChatId: string, multiUserChatPassword: string, partyId: string, partyType: string, restrictions: any[], warnings: any[], };


// --- 从 LobbyMember.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type LobbyMember = { summonerId: string, displayName: string, puuid: string, summonerName: string, summonerLevel: number, summonerIconId: number, isBot: boolean, isLeader: boolean, isSpectator: boolean, ready: boolean, botChampionId: number, botDifficulty: string, botId: string, botPosition: string, firstPositionPreference: string, secondPositionPreference: string, allowedChangeActivity: boolean, allowedInviteOthers: boolean, allowedKickOthers: boolean, allowedStartActivity: boolean, };


// --- 从 LowPriorityData.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type LowPriorityData = { bustedLeaverAccessToken: string, penalizedSummonerIds: Array<bigint>, penaltyTime: number, penaltyTimeRemaining: number, reason: string, };


// --- 从 MatchInfo.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type MatchInfo = { matchId: string, players: Array<PlayerInfo>, };


// --- 从 MatchmakingError.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type MatchmakingError = { errorType: string, id: number, message: string, penalizedSummonerId: bigint, penaltyTimeRemaining: bigint, };


// --- 从 MatchmakingState.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type MatchmakingState = { errors: Array<MatchmakingError>, lowPriorityData: LowPriorityData, searchState: string, estimatedQueueTime: number | null, };


// --- 从 MatchPerformance.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 单场比赛表现
 */
type MatchPerformance = { gameId: number | undefined, win: boolean, championId: number, championName: string, kills: number, deaths: number, assists: number, kda: number, gameDuration: number | null, gameCreation: number | undefined, queueId: number | undefined, gameMode: string | null, role: string, lane: string, position: string, };


// --- 从 MatchStatistics.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 对局统计信息
 */
type MatchStatistics = { totalGames: number, wins: number, losses: number, winRate: number, avgKills: number, avgDeaths: number, avgAssists: number, avgKda: number, favoriteChampions: Array<ChampionStats>, recentPerformance: Array<RecentGame>, };


// --- 从 MultiPositionAnalysis.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ⭐ v3.4: 多位置分组分析结果
 */
type MultiPositionAnalysis = { 
/**
 * 所有位置的统计（按场次从多到少排序）
 */
positionStats: Array<PositionStats>, 
/**
 * 主要位置（场次最多的）
 */
mainPosition: string, 
/**
 * 总览数据（所有位置合计）
 */
overallStats: PlayerMatchStats, };


// --- 从 OpggApiResponse.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * OP.GG API 响应
 */
type OpggApiResponse<T> = { success: boolean, data: T | null, error: string | null, };


// --- 从 OpggChampionBuild.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * OP.GG 英雄详细数据
 */
type OpggChampionBuild = { summary: OpggChampionSummary, summonerSpells: Array<OpggSummonerSpell>, championSkills: OpggSkills, items: OpggItems, counters: OpggCounters, perks: Array<OpggPerk>, };


// --- 从 OpggChampionSummary.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 英雄摘要信息
 */
type OpggChampionSummary = { name: string, championId: number, icon: string, position: string, winRate: number | null, pickRate: number | null, banRate: number | null, kda: number | null, tier: string | null, rank: number | null, };


// --- 从 OpggCounter.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 克制英雄
 */
type OpggCounter = { championId: number, winRate: number, };


// --- 从 OpggCounters.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 克制关系
 */
type OpggCounters = { strongAgainst: Array<OpggCounter>, weakAgainst: Array<OpggCounter>, };


// --- 从 OpggItem.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 装备项目
 */
type OpggItem = { id: number, ids: Array<number>, icons: Array<string>, win: number, play: number, pickRate: number, };


// --- 从 OpggItems.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 装备数据
 */
type OpggItems = { startItems: Array<OpggItem>, coreItems: Array<OpggItem>, boots: Array<OpggItem>, lastItems: Array<OpggItem>, };


// --- 从 OpggPerk.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 符文配置
 */
type OpggPerk = { primaryId: number, secondaryId: number, perks: Array<number>, win: number, play: number, pickRate: number, };


// --- 从 OpggSkills.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 英雄技能
 */
type OpggSkills = { masteries: Array<string>, order: Array<string>, play: number, win: number, pickRate: number, };


// --- 从 OpggSummonerSpell.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 召唤师技能
 */
type OpggSummonerSpell = { spellId: number, ids: Array<number>, win: number, play: number, pickRate: number, };


// --- 从 OpggTierList.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 层级列表
 */
type OpggTierList = { meta: OpggTierListMeta, data: Array<OpggTierListItem>, };


// --- 从 OpggTierListItem.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 层级列表项
 */
type OpggTierListItem = { championId: number, name: string, tier: string, rank: number, winRate: number, pickRate: number, banRate: number, };


// --- 从 OpggTierListMeta.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 层级列表元数据
 */
type OpggTierListMeta = { version: string, region: string, mode: string, tier: string, };


// --- 从 ParticipantInfo.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type ParticipantInfo = { participantId: number, championId: number, summonerName: string, profileIconId: number, teamId: number, rankTier: string | null, stats: ParticipantStats, score: number | null, };


// --- 从 ParticipantStats.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type ParticipantStats = { kills: number, deaths: number, assists: number, champLevel: number, goldEarned: number, totalDamageDealtToChampions: number, totalDamageTaken: number, visionScore: number, item0: number | null, item1: number | null, item2: number | null, item3: number | null, item4: number | null, item5: number | null, item6: number | null, };


// --- 从 Perk.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type Perk = { iconPath: string, id: bigint, longDesc: string, name: string, recommendationDescriptor: string, shortDesc: string, slotType: string, styleId: bigint, styleIdName: string, tooltip: string, };


// --- 从 PlayerAnalysisData.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 玩家完整分析数据（包含战绩）
 */
type PlayerAnalysisData = { cellId: number, displayName: string, summonerId: string | null, puuid: string | null, isLocal: boolean, isBot: boolean, championId: number | null, championName: string | null, championPickIntent: number | null, position: string | null, tier: string | null, profileIconId: number | null, tagLine: string | null, spell1Id: bigint | null, spell2Id: bigint | null, matchStats: PlayerMatchStats | null, };


// --- 从 PlayerInfo.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type PlayerInfo = { summonerName: string, championId: number, teamId: number, };


// --- 从 PlayerMatchStats.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 玩家战绩统计（完整版 - 包含所有分析数据）
 */
type PlayerMatchStats = { totalGames: number, wins: number, losses: number, winRate: number, avgKills: number, avgDeaths: number, avgAssists: number, avgKda: number, todayGames: number, todayWins: number, dpm: number, cspm: number, vspm: number, traits: Array<SummonerTrait>, favoriteChampions: Array<AnalysisChampionStats>, recentPerformance: Array<MatchPerformance>, advice?: Array<GameAdvice>, };


// --- 从 PositionStats.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ⭐ v3.4: 单个位置的统计数据
 */
type PositionStats = { 
/**
 * 位置名称（打野、上单、中单、ADC、辅助、灵活）
 */
position: string, 
/**
 * 该位置的场次
 */
games: number, 
/**
 * 该位置的胜场
 */
wins: number, 
/**
 * 该位置的胜率
 */
winRate: number, 
/**
 * 该位置的统计数据
 */
stats: PlayerMatchStats, };


// --- 从 QueueStats.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type QueueStats = { tier: string, division: string, leaguePoints: number, wins: number, losses: number, };


// --- 从 RankedStats.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type RankedStats = { queueMap: { [key in string]?: QueueStats }, };


// --- 从 RankInfo.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type RankInfo = { soloTier: string | null, soloDivision: string | null, soloLp: number | null, soloWins: number | null, soloLosses: number | null, flexTier: string | null, flexDivision: string | null, flexLp: number | null, flexWins: number | null, flexLosses: number | null, };


// --- 从 RecentGame.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 最近游戏信息
 */
type RecentGame = { gameId: number, championId: number, gameMode: string, win: boolean, kills: number, deaths: number, assists: number, gameDuration: number, gameCreation: number, queueId: number, performanceRating: string, };


// --- 从 RecommendedItem.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 推荐装备项数据结构
 */
type RecommendedItem = { id: string, count: number, };


// --- 从 RuneOption.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type RuneOption = { icon: string, id: number, key: string, longDesc: string, name: string, shortDesc: string, };


// --- 从 RunePage.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 符文页面数据结构
 */
type RunePage = { id: bigint, name: string, current: boolean, isEditable: boolean, isDeletable: boolean, isValid: boolean, primaryStyleId: number, subStyleId: number, selectedPerkIds: Array<number>, };


// --- 从 RunePages.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type RunePages = { pages: Array<DataDragonRune>, };


// --- 从 RuneSet.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type RuneSet = { alias: string, name: string | null, position: string | null, type: string | null, winRate: string | null, pickCount: number | null, score: number | null, primaryStyleId: number | null, subStyleId: number | null, selectedPerkIds: Array<number> | null, };


// --- 从 RuneSlot.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type RuneSlot = { runes: Array<RuneOption>, };


// --- 从 RuneStyle.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type RuneStyle = { allowedSubStyles: Array<bigint>, assetMap: { [key in string]?: string }, defaultPageName: string, defaultPerks: Array<bigint>, defaultSubStyle: bigint, iconPath: string, id: bigint, idName: string, name: string, slots: Array<Slot>, subStyleBonus: Array<SubStyleBonus>, tooltip: string, };


// --- 从 RuneSystem.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type RuneSystem = { icon: string, id: number, key: string, name: string, slots: Array<RuneSlot>, };


// --- 从 SimpleMatchInfo.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 简单对局信息
 */
type SimpleMatchInfo = { gameId: number, championId: number, win: boolean, kills: number, deaths: number, assists: number, gameCreation: number, };


// --- 从 Slot.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type Slot = { perks: Array<bigint>, slotLabel: string, type: string, };


// --- 从 SlotRune.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type SlotRune = { id: bigint; key: string; icon: string; name: string; shortDesc: string; longDesc: string }


// --- 从 SubStyleBonus.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type SubStyleBonus = { perkId: bigint, styleId: bigint, };


// --- 从 SummonerInfo.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type SummonerInfo = { displayName: string, gameName: string | null, tagLine: string | null, summonerLevel: number, profileIconId: number, puuid: string, accountId: string, summonerId: string, xpSinceLastLevel: number, xpUntilNextLevel: number, percentCompleteForNextLevel: number | null, gameStatus: string | null, availability: string | null, challengePoints: string | null, challengeCrystalLevel: string | null, soloRankTier: string | null, soloRankDivision: string | null, soloRankWins: number | null, soloRankLosses: number | null, soloRankLp: number | null, flexRankTier: string | null, flexRankDivision: string | null, flexRankWins: number | null, flexRankLosses: number | null, flexRankLp: number | null, highestRankThisSeason: string | null, currentPerkPage: string | null, primaryStyleId: number | null, subStyleId: number | null, selectedPerkIds: Array<number> | null, };


// --- 从 SummonerTrait.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 召唤师特征标签
 */
type SummonerTrait = { name: string, description: string, score: number, type: string, };


// --- 从 SummonerWithMatches.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type SummonerWithMatches = { displayName: string, summonerInfo: SummonerInfo, matches: PlayerMatchStats, };


// --- 从 TeamAnalysisData.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 队伍分析数据
 */
type TeamAnalysisData = { myTeam: Array<PlayerAnalysisData>, enemyTeam: Array<PlayerAnalysisData>, localPlayerCellId: number, gamePhase: string, queueId: number, isCustomGame: boolean, actions: Array<Array<ChampSelectAction>> | null, bans: ChampSelectBans | null, timer: ChampSelectTimer | null, };


// --- 从 TeamInfo.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type TeamInfo = { teamId: number | null, win: string | null, bans: Array<BanInfo>, baronKills: number | null, dragonKills: number | null, towerKills: number | null, inhibitorKills: number | null, };


// --- 从 TeamStats.ts 同步 ---
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type TeamStats = { kills: number, goldEarned: number, totalDamageDealtToChampions: number, visionScore: number, };


